peel_onion(): add support for <rev>^{tag}
Complete the <rev>^{<type>} family of object descriptors by having
<rev>^{tag} dereference <rev> until a tag object is found (or fail if
unable).

At first glance this may not seem very useful, as commits, trees, and
blobs cannot be peeled to a tag, and a tag would just peel to itself.
However, this can be used to ensure that <rev> names a tag object:

    $ git rev-parse --verify v1.8.4^{tag}
    04f013dc38d7512eadb915eba22efc414f18b869
    $ git rev-parse --verify master^{tag}
    error: master^{tag}: expected tag type, but the object dereferences to tree type
    fatal: Needed a single revision

Users can already ensure that <rev> is a tag object by checking the
output of 'git cat-file -t <rev>', but:
  * users may expect <rev>^{tag} to exist given that <rev>^{commit},
    <rev>^{tree}, and <rev>^{blob} all exist
  * this syntax is more convenient/natural in some circumstances

Signed-off-by: Richard Hansen <rhansen@bbn.com>
Signed-off-by: Junio C Hamano <gitster@pobox.com>

Former-commit-id: 2212d760c7abca216cf63c28a132ca19c8185a97 [formerly fcdc3d8fa1aaea35afea06c56f8ab07e734e919d] [formerly fcdc3d8fa1aaea35afea06c56f8ab07e734e919d [formerly 75aa26d34c4a80142512bd980a416b0fb30044c1]]
Former-commit-id: 9b57d8ce801e266177c613c87dc63e381a3959d5
Former-commit-id: 2544d64c4f5daf3d8469ed28fc4410a0294da35c