t5500: add tests of error output for missing refs
If "git fetch-pack" is called with reference names that do not exist
on the remote, then it should emit an error message

    error: no such remote ref refs/heads/xyzzy

This is currently broken if *only* missing references are passed to
"git fetch-pack".

Signed-off-by: Michael Haggerty <mhagger@alum.mit.edu>
Signed-off-by: Junio C Hamano <gitster@pobox.com>

Former-commit-id: d411d99dcc4790f8a874d86a9fe3b87d854fd36d [formerly 527680540f4d248c68c82994e0ec14eccd0b48db] [formerly 527680540f4d248c68c82994e0ec14eccd0b48db [formerly 3b0820045a68fa84707768528f3af4520fbf3bf0]]
Former-commit-id: 47d134c84f14c4079039b224534ad5fd443605ce
Former-commit-id: 05e3fc26c5acaf2743bac04b4fddc28528158fc4