rm: introduce advice.rmHints to shorten messages
Introduce advice.rmHints to choose whether to display advice or not
when git rm fails. Defaults to true, in order to preserve current behavior.

As an example, the message:
	error: 'foo.txt' has changes staged in the index
	(use --cached to keep the file, or -f to force removal)

would look like, with advice.rmHints=false:
	error: 'foo.txt' has changes staged in the index

Signed-off-by: Mathieu Lienard--Mayor <Mathieu.Lienard--Mayor@ensimag.imag.fr>
Signed-off-by: Jorge Juan Garcia Garcia <Jorge-Juan.Garcia-Garcia@ensimag.imag.fr>
Signed-off-by: Matthieu Moy <Matthieu.Moy@grenoble-inp.fr>
Signed-off-by: Junio C Hamano <gitster@pobox.com>

Former-commit-id: 041237af0d93082fc6cc45686aa942b9ba36f22f [formerly 041237af0d93082fc6cc45686aa942b9ba36f22f [formerly 7e30944622573ebdf87beed057b098af7360234c]]
Former-commit-id: 70cf734579d0e82565cf8fe2faf4edb2bad3a267
Former-commit-id: e6a3eae4ee89dd9d97cbc1c1cc240120d610c9b2