rm: better error message on failure for multiple files
When 'git rm' fails, it now displays a single message
with the list of files involved, instead of displaying
a list of messages with one file each.

As an example, the old message:
	error: 'foo.txt' has changes staged in the index
	(use --cached to keep the file, or -f to force removal)
	error: 'bar.txt' has changes staged in the index
	(use --cached to keep the file, or -f to force removal)

would now be displayed as:
	error: the following files have changes staged in the index:
	    foo.txt
	    bar.txt
	(use --cached to keep the file, or -f to force removal)

Signed-off-by: Mathieu Lienard--Mayor <Mathieu.Lienard--Mayor@ensimag.imag.fr>
Signed-off-by: Jorge Juan Garcia Garcia <Jorge-Juan.Garcia-Garcia@ensimag.imag.fr>
Signed-off-by: Matthieu Moy <Matthieu.Moy@grenoble-inp.fr>
Signed-off-by: Junio C Hamano <gitster@pobox.com>

Former-commit-id: e70c12eb3c8f0a5eb0d19e35c78e65c85bb635b8 [formerly 698abc31c72583816cca6ba86085d8c2c3a19336] [formerly 698abc31c72583816cca6ba86085d8c2c3a19336 [formerly 914dc0289d1df75cfa744cea8ec84cb529cbc791]]
Former-commit-id: 28c9eda822f7be9392ac2c66ccf84f6f0a91fc51
Former-commit-id: 794bdf0f6c261c50d4367c643461ed7cff59d9ea