tree_entry_interesting: match against all pathspecs
The current basedir compare aborts early in order to avoid futile
recursive searches. However, a match may still be found by another
pathspec. This can cause an error while checking out files from a branch
when using multiple pathspecs:

$ git checkout master -- 'a/*.txt' 'b/*.txt'
error: pathspec 'a/*.txt' did not match any file(s) known to git.

Signed-off-by: Andy Spencer <andy753421@gmail.com>
Acked-by: Nguyễn Thái Ngọc Duy <pclouds@gmail.com>
Signed-off-by: Junio C Hamano <gitster@pobox.com>

Former-commit-id: f49bf65f867432a3b1b6a22997eae7e5c55d2e2f [formerly f49bf65f867432a3b1b6a22997eae7e5c55d2e2f [formerly e4ddb05720710213108cd13ddd5a115e12a6211d]]
Former-commit-id: 49e117681d16f7eb195b6a43b191c2184ec89209
Former-commit-id: bf52fe65cb6be3fac55835c32c186ad72972178b