Makefile: remove redundant object in git-http{fetch,push}
revision.o is included in libgit.a which is in $(GITLIBS), so we don't
need to include is separately.  This fixes compilation with
"-fwhole-program" which otherwise fails with messages like this:

  libgit.a(revision.o): In function `mark_tree_uninteresting':
  /home/john/src/git/revision.c:108: multiple definition of `mark_tree_uninteresting'
  /tmp/ccKQRkZV.ltrans2.ltrans.o:/home/john/src/git/revision.c:108: first defined here

Signed-off-by: John Keeping <john@keeping.me.uk>
Signed-off-by: Junio C Hamano <gitster@pobox.com>

Former-commit-id: 646a13e13d9a343648cf848ea343bbcbcb09b8f7 [formerly 646a13e13d9a343648cf848ea343bbcbcb09b8f7 [formerly fd78cedc52a3eab708c1dec2a705b034ddd10d57]]
Former-commit-id: 4828569b7ee4a7d490c24f3fd1daf4f8d83d0ac9
Former-commit-id: fc33addb3d1e9b484315fbb35fd2ec45bda812b6