receive-pack::hmac_sha1(): copy the entire SHA-1 hash out
clang gives the following warning:

builtin/receive-pack.c:327:35: error: sizeof on array function
parameter will return size of 'unsigned char *' instead of 'unsigned
char [20]' [-Werror,-Wsizeof-array-argument]
        git_SHA1_Update(&ctx, out, sizeof(out));
                                         ^
builtin/receive-pack.c:292:37: note: declared here
static void hmac_sha1(unsigned char out[20],
                                   ^
Signed-off-by: Brian Gernhardt <brian@gernhardtsoftware.com>
Signed-off-by: Junio C Hamano <gitster@pobox.com>

Former-commit-id: 7d3f6e8451c9a78076237f8bc1072d904d5b0c45 [formerly 7d3f6e8451c9a78076237f8bc1072d904d5b0c45 [formerly 6f5ef44e0d8933621fcd50127518557013002313]]
Former-commit-id: 44369dee4abdd4d2ff7fac950031239f8d640326
Former-commit-id: c6b013c951f40514040699a85ffd422c7c5e4d12