handle_path_include: don't look at NULL value
When we see config like:

  [include]
  path

the expand_user_path helper notices that the config value is
empty, but we then dereference NULL while printing the error
message (glibc will helpfully print "(null)" for us here,
but we cannot rely on that).

  $ git -c include.path rev-parse
  error: Could not expand include path '(null)'
  fatal: unable to parse command-line config

Instead of tweaking our message, let's actually use
config_error_nonbool to match other config variables that
expect a value:

  $ git -c include.path rev-parse
  error: Missing value for 'include.path'
  fatal: unable to parse command-line config

Signed-off-by: Jeff King <peff@peff.net>
Signed-off-by: Junio C Hamano <gitster@pobox.com>

Former-commit-id: fe5118989726b4c63eca9682be271571f614d946 [formerly fe5118989726b4c63eca9682be271571f614d946 [formerly 67beb600563cf28186f44450e528df1ec4d524fd]]
Former-commit-id: 5379843fed75628193ffbea679691e18e2188a05
Former-commit-id: 61611607bd0c3e24fa9404b33b3d795271ef01c3