run-command: be more informative about what failed
While debugging an error with verify_signed_buffer() the error
messages from run-command weren't very useful:

 error: cannot create pipe for gpg: Too many open files
 error: could not run gpg.

because they didn't indicate *which* pipe couldn't be created.

Print which pipe failed to be created in the error message so we
can more easily debug similar problems in the future.

For example, the above error now prints:

 error: cannot create standard error pipe for gpg: Too many open files
 error: could not run gpg.

Signed-off-by: Stephen Boyd <sboyd@codeaurora.org>
Signed-off-by: Junio C Hamano <gitster@pobox.com>

Former-commit-id: 813a36b5a3264b11b085370be0db4426c26844a2 [formerly 813a36b5a3264b11b085370be0db4426c26844a2 [formerly 939296c4a42b0eb22542f0fe2e50b53993489eff]]
Former-commit-id: 77eec82cc86f3adf37c89a7f52d6570603249d29
Former-commit-id: 7221a46abc375707970f290e4b643452f4932b37